[#15] 노드 간격 조정 및 진행률 박스 사이즈 조정
bconfiden2/MR-monitoring-system pull request #16
Opened 2022-06-27 14:06 UTC by jeonghyeonee

2022-07-01 08:19 UTC, bconfiden2 commented
![image](https://user-images.githubusercontent.com/58922834/176854973-e5571e7c-e1d3-462b-843e-e1d6a284e57f.png)

...   도 중앙정렬이 안맞음

2022-07-01 08:22 UTC, jeonghyeonee commented
아마 전체적으로 중앙정렬이 깨진 것 같아,,,,, 다시 수정할게...!!!!

2022-07-05 05:04 UTC, bconfiden2 requested changes
더미값으로 실행시켰을때, app id 누르면 해당 URL 로 잘 연결돼??

나는 자꾸 고정된 경로로밖에 안가지는디??

예를 들어 app_id 가 1645685868551_18031 이어도 ```http://localhost:4000/164568586855118000``` 여기로 가지고,

1645685868551_18032 일때도 같은 곳으로 가져서!

app_id 자체도 중간에 언더바가 빠지는 문제도 있긴 하고...?

2022-07-05 05:04 UTC, bconfiden2 commented on templates/index.html
> +            {{ data.workers[i] }}<br>
호스트명 중앙정렬 되게끔 하기!

2022-07-05 05:04 UTC, bconfiden2 commented on templates/index.html
>                      {{ data.reducers[i]|length }}
리듀서에도 태스크 박스 똑같이 적용시키기

2022-07-05 05:06 UTC, jeonghyeonee commented
> 

오,,,,언더바 빠지는 건 몰랐다 기다려바 다시 해볼겡

2022-07-05 05:08 UTC, bconfiden2 reviewed
뭐야 1645685868551_18036 를 누르니까 이번엔 값이 50 증가한 ```http://localhost:4000/164568586855118050``` 로 보내졌음!

너쪽에서도 제대로 경로 설정이 안되면 js 쪽에서 값이 제대로 넘어가고 있는건지 콘솔로 디버깅해봐봐!

2023-02-15 06:43 UTC, merged